### ISSUE TITLE
brms_forest help

### ISSUE THREAD

**Issue by tressoldi** [mvuorre/vmisc#1]
[PatrizioData.xlsx](https://github.com/mvuorre/vmisc/files/1560025/PatrizioData.xlsx)
running the following syntax on the attached data

> brms_forest(data = data, study="ExpID", label= "Author", model = fit)

I got this error:

>Error in .f(.x[[i]], ...) : object 'NA' not found

How may I fix it?

**Comment by mvuorre** [comment]
Hi,

You did not specify the variable names for your outcomes and standard errors. Also, your study identifiers ("ExpID") should be unique for each effect size (row). 

For example, this works (I don't know what variables you used in fitting the model, so guessed):

```
library(readxl)
library(brms)
library(vmisc)
d <- read_xlsx("~/Downloads/PatrizioData.xlsx")

fit <- brm(g | se(se) ~ 1 + (1|esID),
           data = d,
           cores = 4, control=list(adapt_delta = .99))

forest <- brms_forest(data = d, 
                      model = fit, 
                      study = "esID", 
                      label = "Author", 
                      yi = "g", 
                      sei = "se", 
                      sort_estimates = TRUE)
forest
```
![forest](https://user-images.githubusercontent.com/7349270/34005408-c47b4600-e0c8-11e7-8da8-d80a03bcb6f4.png)

**Comment by tressoldi** [comment]
May you send me the datafile in order to check how you change it?

**Comment by mvuorre** [comment]
As shown in the above script, I used the data file that you included in your initial issue report.

**Comment by tressoldi** [comment]
Strange, repeating your syntax now I got: 
Error: `by` can't contain join column `esID` which is missing from RHS

I'm using RStudio v. 1.1.383 with R v 3.4.3x64

**Comment by mvuorre** [comment]
Did you fit the model with this syntax?

```
g | se(se) ~ 1 + (1|esID)
```

**Comment by tressoldi** [comment]
This is the syntax:
library(brms)
fit <- brm(g | se(se) ~ 1 + (1|esID),
           data = data,
           cores = 4, control=list(adapt_delta = .99))

library(vmisc)
forest <- brms_forest(data = data, 
                      model = fit, 
                      study = "esID", 
                      label = "Author", 
                      yi = "g", 
                      sei = "se", 
                      sort_estimates = F)

**Comment by mvuorre** [comment]
Hi, I can't reproduce the problem: the code you pasted here works on my computer. Since you didn't include the code on how you created the `data` variable, my guess is you have done something wrong there. The entire (working) reproducible example is here:

```
library(tidyverse)
library(readxl)
data <- read_xlsx("~/Downloads/PatrizioData.xlsx")  # I downloaded this file to my Downloads folder

library(brms)
fit <- brm(g | se(se) ~ 1 + (1|esID),
           data = data,
           cores = 4, control=list(adapt_delta = .99))

library(vmisc)
forest <- brms_forest(data = data,
                      model = fit,
                      study = "esID",
                      label = "Author",
                      yi = "g",
                      sei = "se",
                      sort_estimates = F)
forest
```

**Comment by tressoldi** [comment]
The mystery continue....
I used your data importation method and syntax, but I got the same error message:
Error: `by` can't contain join column `esID` which is missing from RHS

I'm using brms v 1.10.2,  just in case it may serve.

**Comment by mvuorre** [comment]
What version of `vmics` package do you have? Try installing the latest:

```
devtools::install_github("mvuorre/vmisc")
```

**Comment by tressoldi** [comment]
Fixed !!! Evviva
Thank you very much for your collaboration and patience.
All the best

**Comment by mvuorre** [comment]
I am glad we found a solution to your problem.
